version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      APACHE_LOG_DIR: /var/log/apache2
    networks:
      - webnet
    user: www-data

networks:
  webnet:
    driver: bridge
